# Numpy

In [4]:

numbers_lst = [1,2,3]
numbers_lst = numbers_lst*2
print(numbers_lst)

mixed_lst = [1, "ett", True, 2.3]
print(mixed_lst)

[1, 2, 3, 1, 2, 3]
[1, 'ett', True, 2.3]


In [13]:
import numpy as np


vector1 = np.array([2,5,1])
print(vector1)
vector2 = vector1*2
print(vector2)

print(f"{vector1+2=}")
print(f"{vector1[2]=}")
print(f"{vector1[::-1]=}")

vector1[1] = 23
print(vector1)

vector1.sort()
print(f"{vector1=}")

print(f"{vector1.sum()=}")
print(f"{vector1.mean()=}")




[2 5 1]
[ 4 10  2]
vector1+2=array([4, 7, 3])
vector1[2]=1
vector1[::-1]=array([1, 5, 2])
[ 2 23  1]
vector1=array([ 1,  2, 23])
vector1.sum()=26
vector1.mean()=8.666666666666666


In [18]:

ones_vector = np.ones(10)
print(f"{ones_vector=}")

matrix_3x3 = np.ones((3,3))
print(f"{matrix_3x3}")

matrix_3x3[2,1] = 10
print(f"{matrix_3x3}")



ones_vector=array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1. 10.  1.]]


In [19]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:

print(matrix_3x3.shape)
print(matrix_3x3[2,:])
print(matrix_3x3[:,1])

matrix_3x3[2,:] + matrix_3x3[:,1]

(3, 3)
[ 1. 10.  1.]
[ 1.  1. 10.]


array([ 2., 11., 11.])

In [27]:

dices = np.random.randint(1, 7, 100)
dices


array([1, 3, 5, 1, 2, 6, 6, 5, 6, 3, 5, 5, 1, 1, 2, 4, 2, 6, 1, 6, 2, 2,
       5, 1, 6, 6, 2, 4, 4, 3, 2, 6, 6, 1, 3, 3, 4, 3, 3, 6, 1, 3, 3, 5,
       1, 2, 4, 3, 3, 5, 2, 4, 4, 4, 4, 5, 4, 3, 4, 4, 5, 4, 5, 6, 5, 6,
       3, 4, 3, 5, 5, 2, 2, 1, 3, 2, 4, 1, 1, 6, 1, 1, 1, 1, 2, 3, 3, 3,
       6, 2, 3, 6, 2, 3, 1, 1, 2, 1, 5, 1])

In [30]:

x = np.linspace(-5,5)
print(x.shape)
x

(50,)


array([-5.        , -4.79591837, -4.59183673, -4.3877551 , -4.18367347,
       -3.97959184, -3.7755102 , -3.57142857, -3.36734694, -3.16326531,
       -2.95918367, -2.75510204, -2.55102041, -2.34693878, -2.14285714,
       -1.93877551, -1.73469388, -1.53061224, -1.32653061, -1.12244898,
       -0.91836735, -0.71428571, -0.51020408, -0.30612245, -0.10204082,
        0.10204082,  0.30612245,  0.51020408,  0.71428571,  0.91836735,
        1.12244898,  1.32653061,  1.53061224,  1.73469388,  1.93877551,
        2.14285714,  2.34693878,  2.55102041,  2.75510204,  2.95918367,
        3.16326531,  3.36734694,  3.57142857,  3.7755102 ,  3.97959184,
        4.18367347,  4.3877551 ,  4.59183673,  4.79591837,  5.        ])

In [32]:
import matplotlib.pyplot as plt

f = lambda x: x+2

print(f(x))
plt.plot(x,f(x))

ImportError: cannot import name '_docstring' from partially initialized module 'matplotlib' (most likely due to a circular import) (c:\Users\Rasmus\.virtualenvs\Python-Rasmus-Johansson-EWxhOLhb\lib\site-packages\matplotlib\__init__.py)

## Performance

In [35]:
%%timeit
import random as rnd

number_dices = 1_000_000

many_dices = []

for dice in range(number_dices):
    many_dices.append(rnd.randint(1,6))

many_dices

1.27 s ± 105 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [38]:
%%timeit
import random as rnd

number_dices = 1_000_000

many_dices = [rnd.randint(1,6) for _ in range(number_dices)]

1.15 s ± 98.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [41]:
%%timeit
import numpy

number_dices = 1_000_000

many_dices = np.random.randint(1, 7, number_dices)

14.3 ms ± 52 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
